### PR TITLE
fix in examples the curve import 

### PR DESCRIPTION
**Pull request by lottilotte**
for curve examples import directly from compas as NurbsCurve instead of  compas_occ as OCCNurbsCurve

### CODE REVIEW

**Comment by tomvanmele** [comment]
not sure this is something we want to do here in the package

**Comment by tomvanmele** [comment]
perhaps add it in a commented line below to show that this is possible, but it is not mandatory if you are working directly with `compas_occ`, which is what we are documenting here...

btw, the type of curve will be an OCC curve in both cases.

**Comment by lottilotte** [comment]
ok, sorry misunderstanding. should I then just close the PR?

**Comment by tomvanmele** [comment]
yes please

**Pull request closed without merging**
